// Re-export types from the API client
export type {
  ApiResponse,
  AuthData,
  SessionData,
  RefreshTokenData,
  RegisterData,
  BalanceData,
  AccountDetails,
  UserProfile,
  Transaction,
  TransactionStats,
  TransferData,
  DepositData,
  WithdrawData,
  BillPaymentData,
  BillHistoryItem,
  Card,
  CardPIN,
  LoanApplication,
  ProfileUpdate,
  SystemStats,
  AdminUser,
  UserDetails,
  TransactionTrend,
  UserActivity,
  SearchResult,
} from '../client/api.client';
